require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EmpresaAereasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # EmpresaAerea. As you add validations to EmpresaAerea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmpresaAereasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all empresa_aereas as @empresa_aereas" do
      empresa_aerea = EmpresaAerea.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:empresa_aereas)).to eq([empresa_aerea])
    end
  end

  describe "GET show" do
    it "assigns the requested empresa_aerea as @empresa_aerea" do
      empresa_aerea = EmpresaAerea.create! valid_attributes
      get :show, {:id => empresa_aerea.to_param}, valid_session
      expect(assigns(:empresa_aerea)).to eq(empresa_aerea)
    end
  end

  describe "GET new" do
    it "assigns a new empresa_aerea as @empresa_aerea" do
      get :new, {}, valid_session
      expect(assigns(:empresa_aerea)).to be_a_new(EmpresaAerea)
    end
  end

  describe "GET edit" do
    it "assigns the requested empresa_aerea as @empresa_aerea" do
      empresa_aerea = EmpresaAerea.create! valid_attributes
      get :edit, {:id => empresa_aerea.to_param}, valid_session
      expect(assigns(:empresa_aerea)).to eq(empresa_aerea)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmpresaAerea" do
        expect {
          post :create, {:empresa_aerea => valid_attributes}, valid_session
        }.to change(EmpresaAerea, :count).by(1)
      end

      it "assigns a newly created empresa_aerea as @empresa_aerea" do
        post :create, {:empresa_aerea => valid_attributes}, valid_session
        expect(assigns(:empresa_aerea)).to be_a(EmpresaAerea)
        expect(assigns(:empresa_aerea)).to be_persisted
      end

      it "redirects to the created empresa_aerea" do
        post :create, {:empresa_aerea => valid_attributes}, valid_session
        expect(response).to redirect_to(EmpresaAerea.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved empresa_aerea as @empresa_aerea" do
        post :create, {:empresa_aerea => invalid_attributes}, valid_session
        expect(assigns(:empresa_aerea)).to be_a_new(EmpresaAerea)
      end

      it "re-renders the 'new' template" do
        post :create, {:empresa_aerea => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested empresa_aerea" do
        empresa_aerea = EmpresaAerea.create! valid_attributes
        put :update, {:id => empresa_aerea.to_param, :empresa_aerea => new_attributes}, valid_session
        empresa_aerea.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested empresa_aerea as @empresa_aerea" do
        empresa_aerea = EmpresaAerea.create! valid_attributes
        put :update, {:id => empresa_aerea.to_param, :empresa_aerea => valid_attributes}, valid_session
        expect(assigns(:empresa_aerea)).to eq(empresa_aerea)
      end

      it "redirects to the empresa_aerea" do
        empresa_aerea = EmpresaAerea.create! valid_attributes
        put :update, {:id => empresa_aerea.to_param, :empresa_aerea => valid_attributes}, valid_session
        expect(response).to redirect_to(empresa_aerea)
      end
    end

    describe "with invalid params" do
      it "assigns the empresa_aerea as @empresa_aerea" do
        empresa_aerea = EmpresaAerea.create! valid_attributes
        put :update, {:id => empresa_aerea.to_param, :empresa_aerea => invalid_attributes}, valid_session
        expect(assigns(:empresa_aerea)).to eq(empresa_aerea)
      end

      it "re-renders the 'edit' template" do
        empresa_aerea = EmpresaAerea.create! valid_attributes
        put :update, {:id => empresa_aerea.to_param, :empresa_aerea => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested empresa_aerea" do
      empresa_aerea = EmpresaAerea.create! valid_attributes
      expect {
        delete :destroy, {:id => empresa_aerea.to_param}, valid_session
      }.to change(EmpresaAerea, :count).by(-1)
    end

    it "redirects to the empresa_aereas list" do
      empresa_aerea = EmpresaAerea.create! valid_attributes
      delete :destroy, {:id => empresa_aerea.to_param}, valid_session
      expect(response).to redirect_to(empresa_aereas_url)
    end
  end

end
