require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReservarPassagensController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ReservarPassagem. As you add validations to ReservarPassagem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReservarPassagensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all reservar_passagens as @reservar_passagens" do
      reservar_passagem = ReservarPassagem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:reservar_passagens)).to eq([reservar_passagem])
    end
  end

  describe "GET show" do
    it "assigns the requested reservar_passagem as @reservar_passagem" do
      reservar_passagem = ReservarPassagem.create! valid_attributes
      get :show, {:id => reservar_passagem.to_param}, valid_session
      expect(assigns(:reservar_passagem)).to eq(reservar_passagem)
    end
  end

  describe "GET new" do
    it "assigns a new reservar_passagem as @reservar_passagem" do
      get :new, {}, valid_session
      expect(assigns(:reservar_passagem)).to be_a_new(ReservarPassagem)
    end
  end

  describe "GET edit" do
    it "assigns the requested reservar_passagem as @reservar_passagem" do
      reservar_passagem = ReservarPassagem.create! valid_attributes
      get :edit, {:id => reservar_passagem.to_param}, valid_session
      expect(assigns(:reservar_passagem)).to eq(reservar_passagem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReservarPassagem" do
        expect {
          post :create, {:reservar_passagem => valid_attributes}, valid_session
        }.to change(ReservarPassagem, :count).by(1)
      end

      it "assigns a newly created reservar_passagem as @reservar_passagem" do
        post :create, {:reservar_passagem => valid_attributes}, valid_session
        expect(assigns(:reservar_passagem)).to be_a(ReservarPassagem)
        expect(assigns(:reservar_passagem)).to be_persisted
      end

      it "redirects to the created reservar_passagem" do
        post :create, {:reservar_passagem => valid_attributes}, valid_session
        expect(response).to redirect_to(ReservarPassagem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reservar_passagem as @reservar_passagem" do
        post :create, {:reservar_passagem => invalid_attributes}, valid_session
        expect(assigns(:reservar_passagem)).to be_a_new(ReservarPassagem)
      end

      it "re-renders the 'new' template" do
        post :create, {:reservar_passagem => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reservar_passagem" do
        reservar_passagem = ReservarPassagem.create! valid_attributes
        put :update, {:id => reservar_passagem.to_param, :reservar_passagem => new_attributes}, valid_session
        reservar_passagem.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested reservar_passagem as @reservar_passagem" do
        reservar_passagem = ReservarPassagem.create! valid_attributes
        put :update, {:id => reservar_passagem.to_param, :reservar_passagem => valid_attributes}, valid_session
        expect(assigns(:reservar_passagem)).to eq(reservar_passagem)
      end

      it "redirects to the reservar_passagem" do
        reservar_passagem = ReservarPassagem.create! valid_attributes
        put :update, {:id => reservar_passagem.to_param, :reservar_passagem => valid_attributes}, valid_session
        expect(response).to redirect_to(reservar_passagem)
      end
    end

    describe "with invalid params" do
      it "assigns the reservar_passagem as @reservar_passagem" do
        reservar_passagem = ReservarPassagem.create! valid_attributes
        put :update, {:id => reservar_passagem.to_param, :reservar_passagem => invalid_attributes}, valid_session
        expect(assigns(:reservar_passagem)).to eq(reservar_passagem)
      end

      it "re-renders the 'edit' template" do
        reservar_passagem = ReservarPassagem.create! valid_attributes
        put :update, {:id => reservar_passagem.to_param, :reservar_passagem => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reservar_passagem" do
      reservar_passagem = ReservarPassagem.create! valid_attributes
      expect {
        delete :destroy, {:id => reservar_passagem.to_param}, valid_session
      }.to change(ReservarPassagem, :count).by(-1)
    end

    it "redirects to the reservar_passagens list" do
      reservar_passagem = ReservarPassagem.create! valid_attributes
      delete :destroy, {:id => reservar_passagem.to_param}, valid_session
      expect(response).to redirect_to(reservar_passagens_url)
    end
  end

end
